### ISSUE TITLE
`If you will not give me a cow, then I will not give you magic bean` error

### ISSUE THREAD

**Issue by dzmitry-lahoda** [oscarlevin/discrete-book#107]
1. http://discrete.openmathbooks.org/dmoi3/sec_intro-statements.html
2. Consider the statement, “If you will give me a cow, then I will give you magic beans.” Decide whether each statement below is the converse, the contrapositive, or neither.
3.d. `If you will not give me a cow, then I will not give you magic bean`
Actual: Neither
Expected: Converse

**Comment by oscarlevin** [comment]
This statement is the _inverse_ of the original; the contrapositive of the converse.  So while it is logically equivalent to the converse, it is not the converse, which would be "If I give you magic beans, then you will give me a cow".
