### ISSUE TITLE
"Missing essential data in web dataform:"

### ISSUE THREAD

**Issue by dzmitry-lahoda** [oscarlevin/discrete-book#109]
![image](https://user-images.githubusercontent.com/757125/93660529-98739880-fa58-11ea-9d66-e32c86f8fc00.png)

Approx 19 Sep 2020 6.15 UTC. 

Expected: All exercises text is available regardless of non working thirdparties

**Comment by oscarlevin** [comment]
Can you give me a little more background on this?  When I go to the book's main site (http://discrete.openmathbooks.org/dmoi3/sec_intro-statements.html#gNd) I see the WeBWorK problem as expected.  Is this from a new build of the book?  In that case I likely need to update the build instructions.

**Comment by dzmitry-lahoda** [comment]
it worked for me too, but them was not working for some time, than working again.  the problem that WeBWorK is unstable. and if that businesses will be down, remaining part of books will lost some of its parts online. it is non constant issue, but request for safety of online book against WeBWorK down.

**Comment by oscarlevin** [comment]
Thanks.  I'll leave this open for now and keep an eye on it.  I'm not sure how often this shows up.  In the next edition, PreTeXt should be set up to display a static version and only display webwork on a click, which should solve the problem.
