### ISSUE TITLE
discretebook-fall2015.pdf, page 85 question 3

### ISSUE THREAD

**Issue by jonjitsu** [oscarlevin/discrete-book#11]
It seems to be missing information. There are no numbers in the question? How many regular ties and bow ties etc while in the solutions there are numbers.

Also for 3d: 
(d) Once you have selected 2 regular and 3 bow ties, in how many orders could you
put the ties on, assuming you must have one of the three bow ties on top?

I don't see why the answer in the solutions is 5!, is this really the correct answer if you must have one of the 3 bow ties on top?

**Comment by oscarlevin** [comment]
That's what I get for moving things around without reading them.  I've made it clearer, and fixed the incorrect answer for part d.
