### ISSUE TITLE
discretebook-fall2015.pdf, page 257 solution 1.8.21c

### ISSUE THREAD

**Issue by jonjitsu** [oscarlevin/discrete-book#12]
There seems to be a miscalculation.

If there are 20 dollars and each student gets at least 1 dollar but no more than 7 should it not be:

20-7=13 dollars left
give 1 to remaining students:
13-4=9
9 dollars left to distribute to 5 students so 13 choose 4 and not 12 choose 4.

Or another way:
Give 1 dollar to each student 20-5 = 15 dollars left
give 1 student 6 more to reach 7 maximum 15-6=9
etc...

**Comment by oscarlevin** [comment]
We want to subtract the ways that one student gets *more* than 7.  That student will get 8, and possibly more.  So at this point we have distributed 8 to that lucky student plus 1 to the remaining 4, for a total of 12.  We have 8 dollars left to distribute to 5 students, in 12 choose 5 ways.  

Or am I missing something?
