### ISSUE TITLE
Coloring chapter typo error

### ISSUE THREAD

**Issue by claudiatang** [oscarlevin/discrete-book#120]
Coloring chapter typo error

**Comment by claudiatang** [comment]
There seem to be 2 typo erros in the colouring chapter in graph theory:
1. P270 of the pdf textbook, the table of Example 4.4.3, KQEC is shown close to KQEB in its column, but not close to KQEB in its row
2. P273 of the textbook, the table of Exercise question 4 (b) , A is shown conflicts with CFJ, but J is shown not conflcts A, while I is shown conflicts A

**Comment by oscarlevin** [comment]
Thanks for the close reading.  I'll get these fixed as soon as I can.
