### ISSUE TITLE
Possible error in Binomial Coefficients exercise 11

### ISSUE THREAD

**Issue by morbidCode** [oscarlevin/discrete-book#126]
Hello,
I am currently learning discrete math using your awsome book. I'm not sure but I think I found an error in one of the solution for exercise 11 of Binomial Coefficients (https://discrete.openmathbooks.org/dmoi3/sec_counting-binom.html):
One of the definition for Binomial Coefficients is: (from n choose k) is the number of lattice paths of length n containing k steps to the right.

Now to exercise 11

> 11.  Gridtown USA, besides having excellent donut shops, is known for its precisely laid out grid of streets and avenues. Streets run east-west, and avenues north-south, for the entire stretch of the town, never curving and never interrupted by parks or schools or the like.
> Suppose you live on the corner of 3rd and 3rd and work on the corner of 12th and 12th. Thus you must travel 18 blocks to get to work as quickly as possible.

Now, if streets run east west, then I think streets should be the steps to the right. Now to the actual question:

> B. Now suppose you want to stop and get a donut on the way to work, from your favorite donut shop on the corner of 10th ave and 8th st. How many routes to work, stopping at the donut shop, can you take (again, ensuring the shortest possible route)? Explain."

My solution is: (from 12 choose 5)(from 6 choose 4). This is because I treated the paths to the donut shop as (from 12 choose 5) because the street corner is 8-3 = 5.
But the actual solution is: (from 12 choose 7)(from 6 choose 2). I think this is because the paths to the donut shop is (from 12 choose 7) because the avenue corner is 10-3 = 7.
But this is wierd. Avenues run from north to south. Looks like they got reversed? I have not done the last 2 questions yet.
Can you confirm the actual directions for street and avenues? Thanks!

**Comment by morbidCode** [comment]
Hello, never mind. This is not an error. Just realized that the 2 solutions are the same through https://www.reddit.com/r/learnmath/comments/yagowy/binomial_coefficients_is_there_an_error_in_the/. I just forgot the pattern of the Binomial Coefficients. Thanks.

**Comment by oscarlevin** [comment]
Yes indeed.  For problems like this, while it doesn't matter if you choose the up or right blocks, it is helpful to be consistent.  I'll check to make sure that the solution doesn't make this more confusing than necessary
