### ISSUE TITLE
Potential rewording for Example 4.2.6

### ISSUE THREAD

**Issue by SerDigby** [oscarlevin/discrete-book#130]
Hi,

**Example 4.2.6** says "_Explain why every tree is a bipartite graph._"
The provided definition of a tree is "a connected graph containing no cycles". By this definition, a single vertex is a tree.
Since a single vertex cannot be bipartite, the question and solution might need to be reworded.

Thanks!

**Comment by oscarlevin** [comment]
Yeah, these "trivial" cases are annoying, and I often forget about them.  So thanks for the heads up and keeping me honest.
