### ISSUE TITLE
Error building edition branch with pretext

### ISSUE THREAD

**Issue by ssjdan27** [oscarlevin/discrete-book#137]
Building the edition branch fails out of the box. I tested this with github codespaces and on my macbook with the appropriate packages, but both run into the same error. I have been unable to find the difference between the main branch and the edition branch that causes the build to fail. The main branch builds just fine on codespaces and my mac. Maybe it is an obvious fix, but I am unable to find the solution as of now. Below is my terminal when attempting to build in codespaces:

@ssjdan27 ➜ /workspaces/discrete-book (edition) $ pretext -v debug build
Generated `/workspaces/discrete-book/codechat_config.yaml`

PreTeXt-CLI version: 2.3.9

PreTeXt project found in `/workspaces/discrete-book`.
warning: Using CLI version 2.3.9 but project's `requirements.txt`
warning: is configured to use 2.3.6. Consider either installing
warning: CLI version 2.3.6 or running `pretext init --refresh`
warning: to update `requirements.txt` to match 2.3.9.
Since no target was supplied, we will use "html".

debug: Building target html with root of tree below None
debug: XML syntax appears well formed.
debug: XML syntax appears well formed.
debug: PreTeXt document did not pass schema validation; unexpected output may result. See .error_schema.log for hints.  Continuing with build.
critical: Opening and ending tag mismatch: p line 225 and m, line 231, column 92
Exception info:
------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pretext/cli.py", line 451, in build
    target.build(clean=clean, generate=not no_generate, xmlid=xmlid)
  File "/usr/local/lib/python3.11/site-packages/pretext/project/__init__.py", line 515, in build
    self.ensure_webwork_reps()
  File "/usr/local/lib/python3.11/site-packages/pretext/project/__init__.py", line 454, in ensure_webwork_reps
    if self.source_element().xpath(".//webwork[@*|*]"):
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pretext/project/__init__.py", line 320, in source_element
    source_doc.xinclude()
  File "src/lxml/etree.pyx", line 2391, in lxml.etree._ElementTree.xinclude
  File "src/lxml/xinclude.pxi", line 64, in lxml.etree.XInclude.__call__
lxml.etree.XIncludeError: Opening and ending tag mismatch: p line 225 and m, line 231, column 92
------------------------
critical: Failed to build.  Exiting...

----------------------------------------------------
While running pretext, the following errors occurred:

critical: Opening and ending tag mismatch: p line 225 and m, line 231, column 92
critical: Failed to build.  Exiting...

**Comment by oscarlevin** [comment]
I am almost certain that this was the result of my pushing a broken version, then fixing it locally, and forgetting to push again.  It should be fixed now.
