### ISSUE TITLE
Typo/Error: Section 3.2 missing reference

### ISSUE THREAD

**Issue by ssjdan27** [oscarlevin/discrete-book#138]
**Describe the error**
Please give a location of the error, and a brief description of what is wrong or confusing.
The missing reference is in the subsets sections in 3.2 (binomial coefficients). I believe that this should be a link that leads to a different section of the textbook.

`Subsets should be familiar, otherwise read over [cross-reference to target(s) "sec_intro-sets" missing or not unique] again.`

**What version of the book are you using?**
4th Edition (Preview)

**Link to paragraph?**
If you are using an online version, you can click on the grey "link" icon in the left margin to copy a link directly to that paragraph.  Otherwise, just leave this blank.

This may not be the perfect link, but it shows the section of where it is located.
https://runestone.academy/ns/books/published/MATH228-Spring24/sec_counting-binom.html#sec_counting-binom-3

**Comment by oscarlevin** [comment]
Thanks for the heads up.  Should be fixed now.
