### ISSUE TITLE
Typo/Error in Chapter 4.1 

### ISSUE THREAD

**Issue by ssjdan27** [oscarlevin/discrete-book#139]
**Describe the error**
Please give a location of the error, and a brief description of what is wrong or confusing.
The typo is in Chapter 4.1. It is in the investigate section at the very beginning of the chapter. The word fo is typed instead of the word of. The typo is trivial, but I figured it is still important to see.

What if I asked you to find the number of $1\times 1000$ strips? Would the method you used to calculate the number fo $1 \times 15$ strips be helpful?

**What version of the book are you using?**
4th Edition

**Link to paragraph?**
If you are using an online version, you can click on the grey "link" icon in the left margin to copy a link directly to that paragraph.  Otherwise, just leave this blank.
https://runestone.academy/ns/books/published/MATH228-Spring24/sec_seq_intro.html#dmoi-4__a-n-seq1

Again, not a perfect link, but it should be enough to show where the typo is located.

**Comment by oscarlevin** [comment]
Thanks.  Fixed in the latest update.
