### ISSUE TITLE
MBX does not allow math mode in list labels

### ISSUE THREAD

**Issue by davidfarmer** [oscarlevin/discrete-book#15]
In GraphTheory.tex you have

\question Consider the following two graphs:
\begin{itemize}
\item[$G_1$:] $V_1=\{a,b,c,d,e,f,g\}$

The $G_1$ label does not seem possible to translate to MBX, because the label
becomes an attribute, and attributes cannot contain tags.

**Comment by oscarlevin** [comment]
I admit this might be a case of me confusing content and formatting in my code.  There is no semantic reason to put the $G_1$ as the list item marker (mostly, although I suppose you could argue that $G_1$, $G_2$, etc describe items in the list), but this made for nice formatting when producing the pdf.  

I can certainly change this to 
\item[] $G_1$: $V_1 = \{a,b,c,d,e,f,g\}$
if that works better.
