### ISSUE TITLE
labes and filenames for chapters and sections

### ISSUE THREAD

**Issue by davidfarmer** [oscarlevin/discrete-book#17]
It is good if the files containing chapters and sections had a meaningful name,
instead of something like "chapter4.(tex or mbx)".

A reasonable approach is to put a LaTeX label on every chapter and section,
and use a version of that label for the filename.  See the mbx files for some examples.

**Comment by oscarlevin** [comment]
Fair point.  I had already used meaningful file names, but not every section had an internal label.  I've fixed this now in case it makes future conversions easier.
