### ISSUE TITLE
Chapter 1 Pg 19 Example 7

### ISSUE THREAD

**Issue by jonjitsu** [oscarlevin/discrete-book#2]
7. (D ∩ C)∪ A ∩ B  {1, 3, 5, 7, 8, 9}. The set contains all elements that are either
in D but not in C or not in both A and B.
* Note the copy/paste did not include the complement symbol *

Should it not also include 10 since the complement of A intersect B is {1,3,5,7,8,9,10}

If not how come?

**Comment by oscarlevin** [comment]
You are absolutely correct.  Thanks for spotting this.  I've fixed it in the typo-fix branch and will merge it soon.
