### ISSUE TITLE
Defined macros not converting

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/discrete-book#20]
In the file "macros-discrete.tex" I define a boatload of new LaTeX macros to speed up typing.  For example: `\def\N{\mathbb N}` so I get a nice blackboard N for the natural numbers.  These definitions do not get implemented correctly in the mbx at some point along the way.  

Would `\newcommand{\N}{\mathbb N}` fix the problem?  Or is this a mathjax issue?

**Comment by davidfarmer** [comment]
Will be fixed in next pull request.

For future reference, it is better to have macros-discrete.tex input into
the main tex file, and not input within the .sty file.

**Comment by oscarlevin** [comment]
Awesome.  I'll keep that tip in mind, but I assume you don't need me to change it prior to your next pull.
