### ISSUE TITLE
"Exercises" inside Activities

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/discrete-book#21]
The questions inside the `\begin{activity} ... \end{activity}` environments should be just items in an ordered list, not given as exercises.  I had `\begin{questions}...\question ...\end{questions}` for easy of copying to my in-class worksheet LaTeX template (although I could easily deal with having this in an enumerate environment).

I can go through my LaTeX and correct this easily enough,  it is worth fixing in the conversion script.

**Comment by davidfarmer** [comment]
I understand that you want them numbered, but in MBX they should be
marked up as the type of object they are.  In LaTeX and HTML
they will be numbered lists.

If there is no example of this in the sample documents, then
please ask the google group for suggestions.

**Comment by oscarlevin** [comment]
I've searched through the documentation and samples and it seems like whenever there are parts to a exercise, these are implemented as ordered lists.  An activity is a type of exercise, so I assume this is also what others would do for parts of an activity.  I'll raise the issue on the google group anyway.

In some sense, I think an ordered list does capture the semantics though: Here is an activity for you.  Complete the following list of tasks (in order).

**Comment by oscarlevin** [comment]
The update from the google group (Rob specifically) is that items inside exercises or activities should be ordered lists.  There is no current or planed "part" or "prompt" tag for this use.

I think this is a fairly easy find/replace for me to do on my own, unless you want to add it to your conversion process.

**Comment by davidfarmer** [comment]
I'd rather not change this until we get to that point in the APEX
conversion.

**Comment by oscarlevin** [comment]
This should be easy to fix myself.
