### ISSUE TITLE
Terms and glossary

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/discrete-book#22]
To create a list of symbols for the book, I used the glossaries package.  The definitions live inside "symbols.tex".  For example, there I have the line

`\newgsym{isom}{\cong}{isomorphic to}` 

which is short for

`\newglossaryentry{isom}{type=symbols,name={\ensuremath{\cong}}, sort=isom, description={isomorphic to}}`

In the text I can type `\gls{isom}` and this inserts `$\cong$` (ensuring math mode) as well as puts the current page as a reference in the list of symbols.

One way or another, this needs to get implemented in the mbx source.

**Comment by davidfarmer** [comment]
The best I can see happening automatically is:

In math mode, replace \gls{isom} by
\isom

Outside math mode replace it by
$\isom$ \index{$\isom$}

where I have used LaTeX notation in both cases.

Let me know if you have a better suggestion.

**Comment by oscarlevin** [comment]
Would you read the definitions from the "symbols.tex" file or just convert \gls{blah} to \blah (or $\blah$, if not in math mode)?  The former is really cool but sounds like a lot of work for what is probably a single use case.  The latter would work only some of the time, as not all my glossary terms are so nice.  For example, \gls{Bkn} should be $\b B^n_k$ (where "\b" is my macro for \mathbold).

I don't use \gls that often in the text, and as it stands now, it is pretty easy to search for them and fix manually (either before or after conversion).

**Comment by davidfarmer** [comment]
The next pull request will just replace "blah" by "\blah".  We can think about automating the symbols
file, but it is a one-time global replacement and so probably is the same amount of work to do
by hand at the end instead of automating.

**Comment by oscarlevin** [comment]
In that case I would rather keep the \gls to help me search and replace all of them.



Sent from my Sprint Samsung Galaxy S7 edge.


-------- Original message --------
