### ISSUE TITLE
TikZ in mbx

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/discrete-book#23]
According to the MBX author guide, there is support for TikZ images in MBX.  The converted mbx files, however, insert an image with some long hash-like codename, and these do not show up in the html.

**Comment by davidfarmer** [comment]
Is it okay to convert
\tikz{...}
to
\begin{tikzpicture}
...
\end{tikzpicture}

**Comment by oscarlevin** [comment]
Absolutely.  As far as I know, those are equivalent.



Sent from my Sprint Samsung Galaxy S7 edge.


-------- Original message --------

**Comment by oscarlevin** [comment]
There are two issues with the mbx version of tikz images as far as I can see (right now it is not working at all).  

To extract the images as svg files which will eventually get loaded by the html files that xsltproc produces, you must run the mbx script on index.mbx.  I do not really understand how this works, but doing so as is produces svg images of the tizk code. 

To fix this, the following needs to be inserted in the `<docinfo>` part of the main mbx file (right after the macros):

`<latex-image-preamble>
  \usepackage{tikz}
  \usetikzlibrary{shapes,decorations,shadows,fadings}
</latex-image-preamble>
`

Or at least something like that to load tikz (this works for my book because those are the command I use to load tikz in LaTeX; I don't know what you would do in general).

The second issue is that you are processing the code inside by `\begin{tikzpicture}...\end{tikzpicture}` environments.  For example, you converted "--" to `<ndash \>`, which does not work.  Somehow the code inside tikzpicture enviroments must be preserved exactly (as I assume you can do for code in the "verbose" environment.

Those two should do it for now.

**Comment by davidfarmer** [comment]
I added the preamble,
and I will preserve the code inside tikzpicture by mapping back
<ndash \>, <amp /> and whatever else I find.  That will be faster
to code.  Later I may go back and do it properly (treating tikzpicture
like a verbatim environment, but actually it is more difficult than
you might think because verbatim is note literally verbatim in MBX).
Let me know if I miss anything.

Pull request soon.

**Comment by oscarlevin** [comment]
Great.  Some other conversion stuff I noticed:

`\v to` became `&tcaron;o`

`\vl{C}` became `\vlC` (and a bunch more like this, removing the braces).

Actually, I thought I'd find a bunch of things like this, but these two seem fairly isolated.  Fixing the ndash should be enough and I can correct minor errors like these by hand.  So consider all this just FYI.

**Comment by davidfarmer** [comment]
Were the \v and \vl{C} happening in tikz?

Those look like substitutions that are only supposed to happen
outside math mode.  But the way I changed how I handle tikz
has lost the fact that it is in math mode.
Will be fixed in next pull request

**Comment by oscarlevin** [comment]
They were inside tikz, but not in math mode.  Other times \v was left alone (in tikz, not in math mode).  But like I said, there were only two tikz environment that it occurred in, so who knows.
