### ISSUE TITLE
parts and part

### ISSUE THREAD

**Issue by davidfarmer** [oscarlevin/discrete-book#24]
Unless you have  more MBX appropriate suggestion for particular cases,
I'm going to convert "parts" into "enumerate" and "part" into "item".

**Comment by oscarlevin** [comment]
That sounds good to me.  In fact, this is how parts of exercises are handled in the sample article: [http://mathbook.pugetsound.edu/examples/sample-article/html/section-12.html](http://mathbook.pugetsound.edu/examples/sample-article/html/section-12.html).
