### ISSUE TITLE
Converting \defbox environments

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/discrete-book#26]
As you probably noticed, I use a custom environment called \defbox to create the obligatory colored boxed definition/theorem/procedure.  These are not really definitions, although that is probably the closest block currently available.  Until we get a specific block for this environment, could we through these all into an unused block type, perhaps "convention"?  And then the first argument should be the title.  That is, for LaTeX:

`\begin{defbox}{Box Title}`

the MBX would be:

`<convention> <title>Box Title</title>`

**Comment by davidfarmer** [comment]
Should be fixed in next pull request, but please check.

Not sure if "convention" is in MBX yet.

**Comment by oscarlevin** [comment]
Thanks.  I just tested it and "convention" works.
