### ISSUE TITLE
Bad grammar on page 30 of fall 2015 version

### ISSUE THREAD

**Issue by jonjitsu** [oscarlevin/discrete-book#3]
In the fall 2015 version on page 30 exercise 13:

At the end of the semester a teacher assigns letter grades to each of her students.
Is this a function? If so, what sets make up the domain and codomain, **and is the
functions be injective, surjective, bĳective, or neither?**

Questionable text in bold.

**Comment by jonjitsu** [comment]
Ok the same thing in exercise 14 and 15

**Comment by oscarlevin** [comment]
Fixed.  I have no idea how that happened/
