### ISSUE TITLE
Error in graph example page 200

### ISSUE THREAD

**Issue by nsarawagi** [oscarlevin/discrete-book#44]
In Chapter 4 - Graph Theory Page 200 below the definition of graph you have an example of graph.
Here we have a graph with four vertices (the letters a, b, c, d) and **four** edges
(the pairs {a, b}, {a, c}, {b, c}, {b, d}, {c, d})).
it should be **five** edges

**Comment by oscarlevin** [comment]
Thanks.  I'll fix it for the next edition.

**Comment by oscarlevin** [comment]
fixed in source on edition branch.
