### ISSUE TITLE
discretebook-fall2015.pdf, page 39, exercise 8

### ISSUE THREAD

**Issue by jonjitsu** [oscarlevin/discrete-book#5]
In bold:

A group of college students were asked about their TV watching habits. Of those
surveyed, 28 students watch Elementary, 19 watch Castle and 24 watch **of** The Mentalist.
Additionally, 16 watch Elementary and Castle, 14 watch elementary and The Mentalist
and 10 watch Castle and The Mentalist. There are 8 students who watch all three
shows. How many students surveyed watched at least one of the shows?

**Comment by oscarlevin** [comment]
Fixed.  Also updated the shows with better, more recent ones.
