### ISSUE TITLE
Missing dot in exercise headings for html

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/discrete-book#53]
After a rebuild, the dot between the chapter and section in the headings for exercises is gone.

**Comment by davidfarmer** [comment]
Do you mean like "33 Exercises" on this page:

http://discrete.openmathbooks.org/dmoi/sec_polyfit.html

Was the dot custom, or from the main CSS?

**Comment by oscarlevin** [comment]
I think this was from my custom xsl file and has nothing to do with css.  I suspect one of the many changes Rob made on his xsl files c9nflicts with what I did.  I will investigate this later today.



Sent from my Sprint Samsung Galaxy Note8.


-------- Original message --------

**Comment by oscarlevin** [comment]
In fact, numbering is all messed up now, including my hacks to get chapter numbering to start at 0, and to get subsections to display with no numbers.  Will need to start over from scratch on the number customization.

**Comment by oscarlevin** [comment]
Fixed, although now there is no number on the "Exercises" subsection (which is fine, probably better).
