### ISSUE TITLE
Induction typo in 2.5

### ISSUE THREAD

**Issue by siliconninja** [oscarlevin/discrete-book#58]
On page 165 of the tablet version (Example 2.5.1), it should say "let P(n) be the statement 1 + 2 + 3 + ... + n = n(n+**1**)/2", not "n(n+2)/2".

**Comment by siliconninja** [comment]
I saw a commit here that fixes this issue: https://github.com/oscarlevin/discrete-book/commit/fb88027f8300161418c7c4694eb111e60b23bfb9
Thanks Oscar Levin! I am closing this issue because it's no longer needed.

**Comment by oscarlevin** [comment]
This is now fixed in source on edition branch.  Thanks @siliconninja for sticking with this one.
