### ISSUE TITLE
Characteristic roots and linearity

### ISSUE THREAD

**Issue by davidfarmer** [oscarlevin/discrete-book#61]
This is maybe a complaint and not an issue that you can directly fix.

I found it unsatisfying that in the characteristic root discussion in Section 2.4,
the fact that the recurrence relation was *linear* was not mentioned.

If I understood how, in general, you addressed the issue of concepts which are
beyond the scope of the book, then I could offer a suggestion of what to say about this.

**Comment by oscarlevin** [comment]
I've added a short discussion about the limits of the characteristic root technique, including mentioning that these are called linear homogeneous with constant coefficients.
