### ISSUE TITLE
Typoes

### ISSUE THREAD

**Issue by StevenGubkin** [oscarlevin/discrete-book#62]
I will start leaving a list of typos here if that is okay.

0.2 Implications contains the phrase "In particualr".

**Comment by oscarlevin** [comment]
Great.  I'll try to correct these for the next edition as you post them.

**Comment by StevenGubkin** [comment]
0.2 exercise 10b is incorrect.  You would need something like "for all x and y, if x<y then there exists z with x<z<y".  As stated, x and y could be equal and there would never be such a z.

**Comment by StevenGubkin** [comment]
0.2 exercise 9 is probably fine, but we had a spirited class discussion about it.  Namely, can one entertain an "empty" domain of discourse?  A student also raised the question that since "For all x, P(x)" is assumed to be true in the first sentence, then isn't "There exists x, P(x) --> For all x, P(x)" automatically true, since implications are automatically true if their conclusion is true?

I think the discussion this question inspired was valuable, but it might be worth noting that the issues involved are subtle.

**Comment by oscarlevin** [comment]
These have been fixed for the 3rd edition.  If you have more, please open a new issue.  Thanks again for your contribution.
