### ISSUE TITLE
Error in Exercise 0.2.10(b)

### ISSUE THREAD

**Issue by crasmussen-wesleyan** [oscarlevin/discrete-book#63]
The interpretation given in the solution is not correct: the given statement is:

(for all) x (for all) y (exists) z (x < z < y)

and this statement is never true, regardless of the universe of discourse chosen. The given solution to the problem suggests that the English meaning is "Between any two numbers, there exists another number." But that is not the correct meaning; the correct English meaning as written is "Given any number x and any number y, x is less than y and there is another number between them."
Unfortunately, that statement is false in any reasonable universe of discourse. An alternative problem might be:

(for all) x (for all) y (exists) z (x != y) implies (x < z < y) or (y < z < x)

although that is certainly more difficult for students to  #parse.

**Comment by oscarlevin** [comment]
Good point.  I'll fix this for the next edition.  Probably \forall x \forall y (x < y \rightarrow \exists z (x<z<y))
