### ISSUE TITLE
a few small things

### ISSUE THREAD

**Issue by davidfarmer** [oscarlevin/discrete-book#80]
Section 4.1., exercise 15:
Prove that any graph must have two vertices of the same degree.
Need to have at least two vertices.

Example 4.1.1  Has a dangling "equal?" at the end.

I think the right-hand graph immediately above Example 4.1.1
would look better with the baselines of the letters aligned.

Section 2.2, Investigate!:
First row has a colon after the n=2
Second row probably should not be there because it is the same
as the 3rd row, but without the n=0, etc, labels.

In Investigate!s in general:  the bottom on my "Greg's L" is
visible.

There are many places where punctuation is missing at the end
of display math.  Try
`fgrep "</me>" *mbx | grep -v "</me>."`

**Comment by oscarlevin** [comment]
This are now fixed in the source.
