### ISSUE TITLE
Improve the index

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/discrete-book#84]
Working with @mitchkeller and @mattboelkins, we will improve the index for better and more consistent coverage.

Work to be done on "index" branch.  All pull requests should be made into this branch, which will be merged into master and edition when indexing work is complete.

Suggested workflow: Fork and clone discrete-book, checkout index branch.  Then
1. Claim a section by posting on this issue.
1. Create a new branch "index-sec-x-y": `git checkout -b index-sec-x-y`
1. Complete work.
1. Checkout index branch, pull from upstream, checkout index-sec-x-y, rebase index (to incorporate other's work).
1. Push index-sec-x-x to your fork (`git push -u origin index-sec-x-y`); create pull request with base: index.

To build the book to check your work, after setting up makefile.paths, enter `make html-fresh` (you probably just need to do this one time; it will make diagrams and webwork problems) or `make html` (after the first time).

**Comment by mitchkeller** [comment]
I will do section 1.2.

**Comment by oscarlevin** [comment]
I have indexed section 1.1. 

Next I will do chapter 0.

**Comment by mitchkeller** [comment]
Finally at the point where I've got time calendared each week for this. HTML should build for @mattboelkins. Haven't tested LaTeX.

I have sent #91 for 1.2 and will now do 1.3.

**Comment by mitchkeller** [comment]
I have filed #92 for 1.3 and will now move on to 1.4.

**Comment by oscarlevin** [comment]
Thanks @mitchkeller .  Your sections have been pulled in.  I've finished 0.2, and will do 0.3 and 0.4 next.

Are you sure about the assemblage index entries?  When I compile the html, `idx` entries in an `assemblage` get reported as in a "summary" (since I recently renamed assemblage to summary).  Do you have an example to point me to?

Either way, we can wait for Rob to fix it (if needed) and anyway I plan to change almost all the assemblages into either theorems or definitions that will get styled like assemblages, as part of the HTML styling work that we are doing right now with David.

**Comment by mitchkeller** [comment]
Let me pull the latest PTX when I'm on my home computer this evening and see. Perhaps there's an update I'm missing that fixed this, because I was definitely *only* seeing `subsection` in the index for things where I had put an `idx` inside an `assemblage`.

**Comment by davidfarmer** [comment]
Not sure if this is an example, but there are PreTeXt environments
which are/were not handled properly for idx entries: the reference goes
to the parent (sub)section.

We need Rob to fix that bug.  We should not change the markup just
to get around that bug.

This issue says it is closed, but is it fixed?
https://github.com/rbeezer/mathbook/issues/753

**Comment by mitchkeller** [comment]
Assuming the October 2 on which that was fixed is 2019 (I'm having issues telling, since the issue was opened in 2017.), then I suspect that it's just that I haven't pull PTX since Rob added that fix. I'll confirm tonight.

**Comment by mitchkeller** [comment]
Yup. Outdated PreTeXt was the culprit. I now see "Summary" in the index (with a functional knowl) for the `assemblage`s with `idx` inside.

**Comment by mitchkeller** [comment]
Picking up with 1.5.

**Comment by mitchkeller** [comment]
Working on 1.6 next.

**Comment by mitchkeller** [comment]
1.7 had no index-worthy content, as mentioned in #96. Thus, Chapter 1 is now done.

**Comment by oscarlevin** [comment]
Chapters 0 and 1 are done (mod copy editing).

I'll move on to chapter 3 and 4.  @mitchkeller, do you want to tackle chapter 2?  

I propose we ignore chapter 5 as this is in such a need of a rewrite anyway, I'd rather not have anyone find it through the index.

**Comment by mitchkeller** [comment]
Ooh! We get to skip chapters for indexing because they need to be rewritten?! I have one or two of those when we get to my book, too.

Yes, I will do Chapter 2.

**Comment by mattboelkins** [comment]
Gentlemen,

I've proved an unworthy partner here.  Apologies for my long absence from
the discussion.  About two weeks ago I entered end-of-term survival mode.

What can I do to contribute?

Matt

**Comment by oscarlevin** [comment]
No worries.  @mattboelkins , do you want to start on chapter 3?  I'll move on to chapter 4.

**Comment by mattboelkins** [comment]
I'll start on chapter 3 next week.  Thanks for your patience @Oscar Levin
<oscarlevin@gmail.com>

I hope you're both enjoying a real break.

Matt

**Comment by mitchkeller** [comment]
I have just sent the PR #99 to get the indexing of Chapter 2 done.

**Comment by oscarlevin** [comment]
I finally got around to approving @mitchkeller 's chapter 2 pull request.  I'm going to do Chapter 4 today and would be happy to knock out chapter 3 at the same time, unless you have some partial work on this, @mattboelkins.

**Comment by mattboelkins** [comment]
I don't have any partial work on it.  And I think I'm going to have to pass
on this.  C19 has made a real mess of my work life at GVSU, and normal time
that I have in the summer to work on writing projects looks to have
vanished.

Thanks for your understanding, Oscar.

Matt
