### ISSUE TITLE
LaTeX fails to build

### ISSUE THREAD

**Issue by mitchkeller** [oscarlevin/discrete-book#86]
`custom-latex.xsl` attempts to import `../../mathbook/xsl/latex/pretext-latex-dmoi.xsl`, which doesn't get shipped as part of the repo as best as I can tell. What we do with the Active books is cp that file into the PTXXSL directory as one of the first steps of the appropriate `make` target. In reality, I think all the `custom-*.xsl` files should get copied over before invocation so that you don't have XSL files assuming a specific directory structure.

**Comment by oscarlevin** [comment]
I think I've fixed the specific issue (by copying pretext-latex-dmoi.xsl) to my custom xsl directory.  Of course this still assumes that you have the "standard" directory structure to pull in mathbook-latex.xsl.  

I need to look at what you do for Active Calculus.  Are you copying the custom-latex.xsl into mathbook/xsl/, or copying mathbook/xsl into your custom xsl directory?  Both seem like they might lead to issues with pull requests (for mathbook or your project).

**Comment by oscarlevin** [comment]
This should be fixed now.  Thanks @mitchkeller for pushing me on this and providing the nice makefile in active calculus to work from.
