### ISSUE TITLE
Example 4.1.2 is different in the online version and the pdf

### ISSUE THREAD

**Issue by kishvanchee** [oscarlevin/discrete-book#90]
I noticed that the example is different in online version and the pdf. Maybe somewhere the latex source is a typo? Not sure. I haven't delved into the source yet.

PDF:
![example-4-1-2-book](https://user-images.githubusercontent.com/24776049/68531677-edc02300-033a-11ea-9c29-4193540216d8.png)

Online:
![example-4-1-2-online](https://user-images.githubusercontent.com/24776049/68531678-ee58b980-033a-11ea-8fde-aaa27480c102.png)

**Comment by oscarlevin** [comment]
This was recently fixed in the source to update the html version.  The pdf will be updated soon with this fix.

**Comment by kishvanchee** [comment]
Is the html to be considered as the primary source of reference?

**Comment by oscarlevin** [comment]
The goal is to keep the html, pdf, and print editions as consistent as possible.  In this case, since all three were unusable with the glitch, I thought that fixing at least the html would be better than nothing.
